$(document).ready(function(){
  console.log("Ready!");
  $(".ryu").mouseenter(function(){
    $(".ryu-still").hide();
    $(".ryu-ready").show();
  })
  .mouseleave(function(){
    $(".ryu-ready").hide();
    $(".ryu-still").show();
  });
});